version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - ENVIRONMENT=${APP_ENV}
    container_name: marketing-agent-app
    environment:
      - ENVIRONMENT=${APP_ENV}
      - DB_HOST=db
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./:/var/www
    depends_on:
      - db
    networks:
      - app-network 
    ports:
      - "5173:5173"

  nginx:
    image: nginx:stable-alpine
    container_name: marketing-agent-nginx
    ports:
      - "8080:80"      
    volumes:
      - ./:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app-network

  db:
    image: mariadb:latest
    container_name: marketing-agent-db
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network
    ports:
      - "3306:3306"

volumes:
  db-data:

networks:
  app-network:
    driver: bridge